---
# Tasks file for /etc/ansible/apache
- import_tasks: getdata.yml # First task is to get data from the client
- import_tasks: createvm.yml # Second task is to create a VM
- import_tasks: initvm.yml # Third task is to initialize the VM